services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DB__DATABASE_URL=postgresql+asyncpg://${DB__USER}:${DB__PASSWORD}@db:5432/notifications
      - DB__ECHO=TRUE
      - DB__USER=${DB__USER}
      - DB__PASSWORD=${DB__PASSWORD}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB__USER}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
      - POSTGRES_DB=notifications
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
