apiVersion: apps/v1
kind: Deployment
metadata:
    name: notify-service-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: notify-service
    template:
        metadata:
            labels:
                app: notify-service
        spec:
            containers:
                - name: app
                  image: notify-service-app:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 8000
                  env:
                    - name: DATABASE_URL
                      valueFrom:
                        secretKeyRef:
                          name: notify-db-secret
                          key: DB__DATABASE_URL