"""Add status field (Notification table)

Revision ID: 443cf098d122
Revises: 21563c17532b
Create Date: 2026-03-30 16:41:33.855497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "443cf098d122"
down_revision: Union[str, Sequence[str], None] = "21563c17532b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("status", sa.String(length=50), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "status")
    # ### end Alembic commands ###
